### ISSUE TITLE
Ошибка при запуске программы из консоли

### ISSUE THREAD

**Issue by DenVot** [octo-gone/sync-execution#1]
При десериализации файла `.drawio` выходит ошибка. Также пробовал десериализовать `.xml` файл, такая же ошибка. 

Возможно (я просто в питоне не особо разбираюсь), имеет смысл создать отдельный класс, объект которого будет хранить в себе результаты десериализации и уже с ним производить какие-либо действия.

![image](https://user-images.githubusercontent.com/69825463/110318050-0ec38180-801e-11eb-8de2-29899fa202cb.png)

**Comment by octo-gone** [comment]
Добрый день!

Данная ошибка возникает, когда линия, соединяющая узлы, не была подключена правильно (или вообще подключена).

![Пример неправильного подключения](https://user-images.githubusercontent.com/18229436/110327264-cd859e80-802a-11eb-8d57-e85f9d779de4.png)
![Пример ошибки](https://user-images.githubusercontent.com/18229436/110327505-1b9aa200-802b-11eb-8d42-148ab99d28e7.png)

Как видно из примера, на узле `Play` отображается подключение к коннектору, а на `Stop` - нет. Для исправления достаточно соеденить их правильно.

![Пример правильного подключения](https://user-images.githubusercontent.com/18229436/110327582-34a35300-802b-11eb-927b-04a7f17dcd82.png)
![Пример вывода программы](https://user-images.githubusercontent.com/18229436/110327771-77652b00-802b-11eb-9201-f0b6e31afabb.png)

В ближайшее время будет добавлено более понятное отображение ошибок. Спасибо за обратную связь.

**Comment by DenVot** [comment]
Спасибо за объяснение. У меня есть еще один вопрос... Вот так работать будет или нет?

![image](https://user-images.githubusercontent.com/69825463/110328499-7aace680-802c-11eb-9ad0-99985f3528a6.png)

**Comment by octo-gone** [comment]
Да, будет
